site_name: MLModule
theme:
  name: material
  features:
    - content.code.annotate
    - navigation.instant
    - navigation.indexes
    - navigation.tracking
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
repo_url: https://github.com/LSIR/mlmodule
repo_name: LSIR/mlmodule

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - css/mkdocstring.css

plugins:
  - search
  - bibtex:
      bib_file: "docs/references.bib"
  - markdownextradata
  - mkdocstrings:
      handlers:
        python:
          rendering:
            heading_level: 3
            show_root_heading: true
            show_signature_annotations: true
            show_bases: false
            show_source: false
      watch:
        - src/mlmodule

extra:
  develop:
    python_version: 3.7
    pytorch_version: 1.9
    tox_env_version: py37-pt19
  release:
    tox_env_version: "{py37,py38,py39}{-pt19,-pt110}{-cuda,}"

  licenses:
    clip:
      name: CLIP
      link: https://github.com/openai/CLIP/blob/main/LICENSE
    insightface:
      name: InsightFace
      link: https://github.com/deepinsight/insightface#license
    magface:
      name: MagFace
      link: https://github.com/IrvingMeng/MagFace/blob/main/LICENSE
    places365:
      name: Places365
      link: https://github.com/CSAILVision/places365/blob/master/LICENSE
    sbert:
      name: SBERT
      link: https://github.com/UKPLab/sentence-transformers/blob/master/LICENSE
    torchvision:
      name: TorchVision
      link: https://github.com/pytorch/vision/blob/main/LICENSE

  models:
    arcface:
      - name: ArcFace pre-trained by InsightFace
        factory: torch_arcface_insightface
        license: insightface
    clip:
      - name: CLIP pre-trained image encoder
        factory: torch_clip_image_encoder
        license: clip
      - name: CLIP pre-trained text encoder
        factory: torch_clip_text_encoder
        license: clip
    densenet:
      - name: PyTorch DenseNet pre-trained on ImageNet
        factory: torch_densenet_imagenet
        license: torchvision
      - name: PyTorch DenseNet pre-trained on Places365
        factory: torch_densenet_places365
        license: places365
    keyframes:
      - name: Keyframes with ResNet pre-trained on ImageNet
        factory: torch_keyframes_resnet_imagenet
        license: torchvision
      - name: Keyframes with DenseNet pre-trained on ImageNet
        factory: torch_keyframes_densenet_imagenet
        license: torchvision
      - name: Keyframes with DenseNet pre-trained on Places365
        factory: torch_keyframes_densenet_places365
        license: places365
    sentences:
      - name: SBERT's pre-trained DistilUse Multilingual Cased V2
        factory: torch_distiluse_base_multilingual_v2
        license: sbert
    magface:
      - name: Pre-trained MagFace
        factory: torch_magface
        license: magface
    resnet:
      - name: PyTorch ResNet pre-trained on ImageNet
        factory: torch_resnet_imagenet
        license: torchvision
